Improved Help Command
Heptagram-Bot/Heptagram pull request #192
Opened 2021-06-11 04:31 UTC by Uklizdev

Testing your help command I found a bug, the bot would send twice the message with the command list. The code was also very inefficient and the text sent by the bot was kinda ugly. I saw you wanted to keep some commands only for those users who had the Admin role and so I kept that as it was before. This are the results:

 Help for specific command:
![image](https://user-images.githubusercontent.com/71178122/121630944-87d6d880-ca54-11eb-815b-14ea9a73776a.png)

If user has Admin role:
![image](https://user-images.githubusercontent.com/71178122/121630972-93c29a80-ca54-11eb-8e5e-9cafcdba4f5f.png)

If user doesn't have Admin role:
![image](https://user-images.githubusercontent.com/71178122/121630990-9fae5c80-ca54-11eb-8ccd-20c12a9d9f8b.png)

Feel free to change whatever you like, in the design or code.

2021-06-11 04:35 UTC, Uklizdev commented
Oh and also, "Utilitys" should be spelled "Utilities", I didn't change it because its an annoying job, that word is all over the place. 🤣

2021-06-11 23:02 UTC, j-dogcoder requested changes
Overall it looks super good! Thanks for your contribution! 1 thing, The bot doesn't respond with a message in the server. (see screenshot below)



<img width="944" alt="Screen Shot 2021-06-11 at 6 50 53 PM" src="https://user-images.githubusercontent.com/65788728/121756260-80acda80-cae7-11eb-8d52-d9dc3c9d5d34.png">

2021-06-11 23:15 UTC, j-dogcoder commented
Issue #193 is a known issue, but we have staff working on it.

Once you make that slight revision with server message, we will be good to merge @Uklizdev

2021-06-13 01:18 UTC, j-dogcoder approved these changes

2021-06-13 01:19 UTC, merged