Music bot play skip stop functions
Heptagram-Bot/Heptagram pull request #211
Opened 2021-07-06 08:19 UTC by Mert18

Music bot starter. Created music folder under commands, other music bot functionalities will be added here.

2021-07-06 13:05 UTC, j-dogcoder commented
Hey @Mert18! Please make sure to have PR's into the **staged** branch as directed by our [contributing.md](https://github.com/Heptagram-Bot/Heptagram/blob/master/CONTRIBUTING.md)

2021-07-06 13:18 UTC, j-dogcoder commented
Also, I got the below message when running yarn install. Is that something to be concerned about?
<img width="593" alt="Screen Shot 2021-07-06 at 9 16 30 AM" src="https://user-images.githubusercontent.com/65788728/124606452-e700f080-de3a-11eb-9fa5-397963fc21b0.png">

2021-07-06 13:29 UTC, thinkverse requested changes

2021-07-06 13:29 UTC, thinkverse commented on commands/music/play.js
> +		const music = args.join(' ');
What if no URL is provided? Best to add a help message if `args` is empty.
Something along the lines of; `Please provide a YouTube URL to play`.

2021-07-06 13:38 UTC, j-dogcoder requested changes
Thank you for the PR @Mert18! I have a few things.

1. Can these messages be changed to embeds? Most of the bot uses them, and they just look nicer.
2.  Currently the bot reacts to any command it successfully executes, with a ✅. However, It would be great if when in the music commands the user is told something like "you must be in a voice channel", that we could take away the checkmark and replace it with the ❌? [This](https://discordjs.guide/popular-topics/reactions.html#removing-reactions-by-emoji) may be a useful resource for doing that.
3. I try to keep the main.js file as clean as possible. Is there any way to move some of the music bot stuff into a new file? I understand if it isn't, I am just trying to keep things tidy.

Thanks!

2021-07-06 14:03 UTC, Mert18 commented
> Thank you for the PR @Mert18! I have a few things.
> 
> 1. Can these messages be changed to embeds? Most of the bot uses them, and they just look nicer.
> 2. Currently the bot reacts to any command it successfully executes, with a ✅. However, It would be great if when in the music commands the user is told something like "you must be in a voice channel", that we could take away the checkmark and replace it with the ❌? [This](https://discordjs.guide/popular-topics/reactions.html#removing-reactions-by-emoji) may be a useful resource for doing that.
> 3. I try to keep the main.js file as clean as possible. Is there any way to move some of the music bot stuff into a new file? I understand if it isn't, I am just trying to keep things tidy.
> 
> Thanks!

Okay I'll do my best :)

2021-07-06 21:42 UTC, j-dogcoder commented
@Mert18 What are the little problems?

2021-07-06 21:56 UTC, Mert18 commented
First, I have some trouble using Git system since I'm relatively new to Open Source. So forgive me for any problem that I cause :)

All the comments are embeds now.
Replacing emojis with ❌ is a bit problematic. Since ✅ is added after the play.js runs, I can't remove it in play.js file. I'm open to any suggestions.
I tried to move music configurations from main.js file, event handler directories is an option but I wasn't sure.

About Distube npm package, you said you're getting an update error, there is no kind of error in npm, also I checked the official page, there are no signs of it.

2021-07-06 22:02 UTC, Mert18 commented
Oh also, I use the same lines of code in play.js skip.js and stop.js for error handling. When the user is not in a voice channel, error shows up. It seems repetitive, we must find a way to avoid this.

2021-07-07 12:41 UTC, j-dogcoder commented
In terms of being new to git, you'll get used to it quickly! I am hoping that maybe someone from our @Heptagram-Bot/open-source-contributors team could help with the reactions? I have sorted the distube npm error, so that is all fixed. I have no idea about the error. Perhaps if you provide it I can take a closer look? Maybe someone from the team wants to help with that?

2021-07-07 13:42 UTC, Mert18 commented
The error is showing up in embeds, saying You are not in a voice channel (as we expected). But the problem is, the code is repetitive in those three files.

2021-07-07 13:56 UTC, j-dogcoder commented
That's fine!

2021-07-07 13:56 UTC, j-dogcoder commented
Is it just emojis left?

2021-07-07 14:03 UTC, Mert18 commented
Yes. If the command is invalid, the bot react with ❌ but then also reacts with ✅

2021-07-07 20:00 UTC, j-dogcoder approved these changes
This is done for the most part, so I am going to approve it. We can work on emojis and other kinks as needed.

2021-07-07 20:00 UTC, merged