feat: Add welcome/leave messages
Heptagram-Bot/Heptagram pull request #284
Opened 2021-08-10 18:23 UTC by Panquesito7

Things added/changed:

- Add welcome/leave messages (requires two channels named `welcome` and `leaves`).
  - Closes #278.

2021-08-10 20:05 UTC, j-dogcoder requested changes
- See comments
- Can we make the channels and the messages configurable? In the issue, I think there is a guide about that using our mongo database.

2021-08-10 20:05 UTC, j-dogcoder commented on main.js
> +bot.on("guildMemberRemove", member => {
Hey! It's client.on instead of bot.on in this bot.

2021-08-10 20:05 UTC, j-dogcoder commented on main.js
> +bot.on("guildMemberAdd", async member => {
Hey! It's client.on instead of bot.on in this bot.

2021-08-10 20:10 UTC, Panquesito7 commented
> the channels and the messages configurable

We can use a single `config.json` file for that if wanted.

>  In the issue, I think there is a guide about that using our mongo database.

Well, I don't know anything about MongoDB. 😅

2021-08-10 20:13 UTC, j-dogcoder commented
I'd like it to be guild configurable if possible. I'll merge this, and open an issue for making it configurable.

2021-08-11 10:57 UTC, j-dogcoder approved these changes
#286

2021-08-11 18:32 UTC, merged