Issue-176-ReactionRoles
Heptagram-Bot/Heptagram pull request #327
Opened 2021-10-01 08:34 UTC by anubhav06

# Pull Request

## Description

Added Reaction Role Command. 
User can create an embed and then add the reaction-role pair as required by the user. Command usage is mentioned
in the file `reaction.js`

## Related Issue

Closes #176 

## Scope

Did you remember to update the `package.json` version number?

- [ ] Major Version Update: X.\_.\_ (for complete code refactors, or large PRs that adjust most of the codebase)
- [x] Minor Version Update: \_.X.\_ (for the addition of new commands)
- [ ] Patch Version Update: \_.\_.X (for bug fixes _in the code_.)
- [ ] No Version Update: \_.\_.\_ (no version update for additions to tests, documentation, or anything that isn't end-user facing.)

## Documentation

For _any_ version updates, please verify if the documentation page needs an update. If it does, please create an issue to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [] My contribution DOES require a documentation update.

2021-10-01 11:17 UTC, j-dogcoder requested changes

2021-10-01 11:17 UTC, j-dogcoder commented on package.json
> +  "version": "1.1.0",
Can this move to 1.2.0? We have another PR before this that needs to be merged.

2021-10-01 11:34 UTC, j-dogcoder commented
@Mergifyio rebase

2021-10-01 11:35 UTC, j-dogcoder commented
@Mergifyio rebase

2021-10-01 12:40 UTC, anubhav06 commented
Do I need to make any changes to the commits or is it resolved ?

2021-10-01 13:42 UTC, j-dogcoder commented
It is resolved, I just need to merge it. I will do that super soon.

2021-10-01 18:40 UTC, j-dogcoder approved these changes

2021-10-01 18:40 UTC, merged

2021-10-01 18:41 UTC, j-dogcoder commented
LGTM @anubhav06! 🎉

2021-10-04 23:02 UTC, Panquesito7 commented on commands/Resources and Utilitys/reaction.js
> +						message.reply(`The mentioned role: "${role}" does not exist`);
```suggestion
						message.reply(`The role "${role}" does not exist`);
```

2021-10-04 23:02 UTC, Panquesito7 commented on commands/Resources and Utilitys/reaction.js
> +};
Missing an endline.
```suggestion
};

```

2021-10-04 23:13 UTC, Panquesito7 commented
Was this PR reverted? I do not see this anywhere in the repository. 👀

2021-10-05 01:50 UTC, j-dogcoder commented
It is staged in the stage branch, just not on master yet @Panquesito7